'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={time_localization:'时间定位',speaker_content:'谁说了什么',content_context_A:'会议内容',content_context_B:'晚餐内容',speaker_counts:'各组人数'};
let data,meta,resultData,listeningData,answers=null,current='SC001',listenVariant='dual';
const listenVariants={singleA:'1 context · 单独 A',singleB:'1 context · 单独 B',dual:'2 contexts · A+B',triple:'3 contexts · A+B+干扰',quadruple:'4 contexts · A+B+两路干扰'};
const sourceNames={A:'会议组 A · NOTSOFAR',B:'晚餐组 B · CHiME-6',C:'朗读 C · LibriSpeech',D:'朗读 D · LibriSpeech'};
const sourceColors={A:'#295eda',B:'#b7683b',C:'#427b60',D:'#8561a8'};
function listenPath(id=current,variant=listenVariant){return `listen/${id}/${variant}`;}
const selections=new Map(),submitted=new Set();
async function loadJSON(path){const r=await fetch(path,{cache:'no-cache'});if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json();}
const sample=()=>data.samples.find(s=>s.id===current);
function route(){const raw=location.hash.slice(1);const parts=raw.split('/');const view=['results','about'].includes(parts[0])?parts[0]:'listen';if(parts[1]&&data.samples.some(s=>s.id===parts[1]))current=parts[1];for(const v of ['listen','results','about']){$(`#${v}-view`).hidden=v!==view;$(`#nav-${v}`).classList.toggle('active',v===view);}if(view==='listen'){listenVariant=Object.hasOwn(listenVariants,parts[2])?parts[2]:'dual';renderSample();}if(view==='results')renderResults();}
function renderList(){$('#sample-list').innerHTML=data.samples.map((s,i)=>`<button class="sample-button ${s.id===current?'selected':''}" data-sample="${s.id}" aria-pressed="${s.id===current}"><span class="sample-number">${String(i+1).padStart(2,'0')}</span><span class="sample-name">${esc(meta.samples[i].title)}<small>${s.id} · 60 秒</small></span></button>`).join('');$('#sample-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{location.hash=listenPath(b.dataset.sample);});}
function roomSVG(m,v){let s='<svg class="room" viewBox="0 0 240 170" role="img" aria-label="虚拟房间俯视图：空间版声源示意图，听者面向前方"><defs><pattern id="grid" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M22 0H0V22" fill="none" stroke="#e6ecf2" stroke-width=".5"/></pattern></defs><rect x="15" y="12" width="210" height="145" rx="5" fill="url(#grid)" stroke="#c9d6e3"/><path d="M120 105L113 119H127Z" fill="#283f52"/><text x="105" y="139" fill="#60727c" font-size="9">听者</text>';
for(const ctx of v.contexts){const angle=v.audio.spatial.azimuth_deg[ctx]*Math.PI/180,p=m.room.source_xyz_m[ctx]??[3-2*Math.sin(angle),2+2*Math.cos(angle),1.5];const x=15+p[0]/6*210,y=157-p[1]/5*145,color=sourceColors[ctx];s+=`<path d="M120 112L${x} ${y}" stroke="${color}" opacity=".35" stroke-dasharray="3 3"/><circle cx="${x}" cy="${y}" r="14" fill="${color}" opacity=".1"/><circle cx="${x}" cy="${y}" r="6" fill="${color}"/><text x="${x-13}" y="${y-20}" font-size="10" fill="${color}">${ctx==='A'||ctx==='B'?'组':'朗读'} ${ctx}</text>`;}return s+'</svg>';}
function renderSample(){renderList();const s=sample(),m=meta.samples.find(x=>x.id===s.id),v=listeningData.samples.find(x=>x.id===s.id).variants[listenVariant];const done=submitted.has(current);$('#sample-content').innerHTML=`<section class="panel"><div class="sample-header"><div><span class="sample-id">${s.id} / ${v.context_count} CONTEXT${v.context_count>1?'S':''}</span><h2>${esc(m.title)}</h2><div class="tags"><span class="tag">60 秒</span><span class="tag">48 kHz · 双声道</span><span class="tag">5 道题</span></div></div><button class="share-btn" id="share">分享此样例 ↗</button></div><div class="listen-controls"><label for="listen-variant">音频版本</label><select id="listen-variant">${Object.entries(listenVariants).map(([key,label])=>`<option value="${key}" ${key===listenVariant?'selected':''}>${label}</option>`).join('')}</select><span>${v.contexts.join(' + ')}</span></div><div class="room-row">${roomSVG(m,v)}<div class="room-copy">${v.contexts.map(ctx=>`<p><span style="color:${sourceColors[ctx]}">● ${sourceNames[ctx]}</span></p>`).join('')}<p>空间版方位：${v.contexts.map(ctx=>`${ctx} ${v.audio.spatial.azimuth_deg[ctx]}°`).join('，')}。<br>同位置版各声源均在正前方。</p></div></div><div class="players">${[['spatial','空间版','保留原空间方位 · 建议耳机'],['colocated','同位置对照','同一正前方 · 保留评测增益']].map(([c,title,sub])=>`<div class="player"><h3>${title}</h3><p>${sub}</p><audio controls preload="none" src="${esc(v.audio[c].file)}" aria-label="${s.id} ${listenVariants[listenVariant]} ${title}"></audio><a href="${esc(v.audio[c].file)}" download>↓ 下载${v.audio[c].format==='FLAC'?'无损 FLAC':'原始 WAV'}</a></div>`).join('')}</div><p class="note">${v.context_count===1?'单独 A 对应第 1–3 题，单独 B 对应第 4 题；第 5 题请分别听 A/B 后作答。':'五道题与正确答案不变；新增 C/D 仅作干扰，人数题仍只统计 A/B。'} 评测时人数题拆成 A/B 两个子问，均正确才计分。</p></section><section class="panel"><div class="questions-top"><h3>听完，试着回答</h3><small>每题四选一 · 各音频版本共用题目</small></div><form id="quiz">${s.questions.map((q,i)=>`<section class="question" id="${q.id}"><div class="q-meta"><span>QUESTION ${i+1} / 5</span><span class="q-type">${types[q.type]}</span></div><p class="q-text">${esc(q.question)}</p><div class="options">${q.options.map((o,j)=>`<label class="option"><input type="radio" name="${q.id}" value="${j}" ${selections.get(q.id)===j?'checked':''}><span class="letter">${'ABCD'[j]}</span><span>${esc(o)}</span></label>`).join('')}</div><div class="answer-slot"></div></section>`).join('')}<div class="quiz-actions"><button class="primary" type="submit">检查我的答案</button><button class="secondary" id="reveal" type="button">查看答案与证据</button><span class="score" id="score" role="status"></span></div></form><p class="note">作答仅在当前浏览器页面中保留。查看答案后仍可重新选择并评分。</p></section>`;
$('#listen-variant').onchange=e=>{location.hash=listenPath(current,e.target.value);};
$('#share').onclick=async()=>{const url=new URL(location.href);url.hash=listenPath();try{await navigator.clipboard.writeText(url.href);$('#share').textContent='链接已复制';}catch{$('#share').textContent='复制地址栏即可分享';}};
$('#quiz').onchange=e=>{if(e.target.type==='radio')selections.set(e.target.name,Number(e.target.value));};
$('#quiz').onsubmit=async e=>{e.preventDefault();try{await showAnswers(true);}catch{$('#score').textContent='答案加载失败，请重试。';}};
$('#reveal').onclick=async()=>{try{await showAnswers(false);}catch{$('#score').textContent='答案加载失败，请重试。';}};
document.querySelectorAll('audio').forEach(a=>a.onplay=()=>document.querySelectorAll('audio').forEach(b=>{if(a!==b)b.pause();}));
if(done&&answers)showAnswers(true);
}
async function showAnswers(score){if(!answers)answers=await loadJSON('answers.json');const s=sample();const g=answers.samples.find(x=>x.id===s.id);let correct=0,answered=0;for(const a of g.answers){const q=document.getElementById(a.id),selected=selections.get(a.id);if(selected!==undefined){answered++;if(selected===a.answer_index)correct++;}q.querySelectorAll('.option').forEach((label,i)=>{label.classList.toggle('correct',i===a.answer_index);label.classList.toggle('wrong',score&&i===selected&&i!==a.answer_index);});q.querySelector('.answer-slot').innerHTML=`<details class="evidence"><summary>答案 ${a.answer} · 展开逐句证据</summary>${a.evidence.map(e=>`<p><small>${esc(e.row_id)} · ${Number(e.start).toFixed(2)}–${Number(e.end).toFixed(2)} 秒 · ${esc(e.speaker)}</small><br>${esc(e.clean_text)}</p>`).join('')}</details>`;}if(score){submitted.add(current);$('#score').textContent=`答对 ${correct} / 5 · 已作答 ${answered} / 5${answered<5?'（未答题尚未选择）':''}`;}else $('#score').textContent='已显示参考答案。';}
function getLatestRuns(condition){const latest=new Map();for(const r of [...resultData.runs].sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at))){if(r.condition===condition)latest.set(r.model_id+'|'+r.sample_id,r);}return [...latest.values()];}
function renderSmokeResults(){const rows=resultData.smoke_runs??[],names=new Map(resultData.models.map(m=>[m.id,m.name])),kinds={hear_voice_attribution:'HEAR · 声音归属',notsofar_native_stream:'NOTSOFAR · 原生流式',notsofar_transcription:'NOTSOFAR · 转录',spatial_transcription:'SC001 · 空间版转录'},states={pass:'通过',fail:'失败',blocked:'受阻'};$('#smoke-table').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>模型</th><th>样本</th><th>终态</th><th>结果摘要</th><th>耗时</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(names.get(r.model_id)??r.model_id)}</td><td>${esc(kinds[r.sample_kind]??r.sample_kind)}<small>${Number(r.duration_seconds).toFixed(2)} 秒</small></td><td><span class="pill">${esc(states[r.status]??r.status)}</span></td><td>${esc(r.summary)}</td><td>${r.latency_seconds==null?'—':Number(r.latency_seconds).toFixed(2)+' 秒'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="fineprint">尚无已归档的单样本链路结果。</p>';
const protocols=resultData.model_protocols??[],box=$('#model-protocols');box.hidden=!protocols.length;if(protocols.length)box.innerHTML=`<h3>评测协议</h3><p class="fineprint">一次回答 5 题与每次回答 1 题的协议不同；Muse 每次转录一条音频，仅计算 WER。分数与耗时需结合调用方式解读。</p><div class="table-wrap"><table><thead><tr><th>模型</th><th>每次题数</th><th>模型调用数</th><th>说明</th></tr></thead><tbody>${protocols.map(r=>`<tr><td>${esc(names.get(r.model_id)??r.model_id)}</td><td>${r.questions_per_call??'不适用'}</td><td>${r.inference_calls??'—'}</td><td>${esc(r.prompt_note)}</td></tr>`).join('')}</tbody></table></div>`;}
function renderTranscriptionResults(){
const evaluation=resultData.transcription_evaluation,box=$('#transcription-results');box.hidden=!evaluation;if(!evaluation)return;
const condition=$('#result-condition').value,totals=evaluation.conditions[condition],rows=evaluation.runs.filter(r=>r.condition===condition);
box.innerHTML=`<h3>Muse · 完整标注转录 WER</h3><p>全部 20 条转录已完成 · 20 分钟音频 · 费用 $${Number(evaluation.cost_usd).toFixed(2)}</p><p class="fineprint">${esc(evaluation.note)}</p><p><strong>${condition==='spatial'?'空间版':'同位置对照'} WER ${(totals.wer*100).toFixed(2)}%</strong> · ${totals.completed}/10 条 · 参考 ${totals.reference_words} 词 · 替换 ${totals.substitutions} / 删除 ${totals.deletions} / 插入 ${totals.insertions}</p><div class="table-wrap"><table><thead><tr><th>样例</th><th>WER</th><th>替换 / 删除 / 插入</th><th>参考词数</th><th>耗时</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.sample_id)}</td><td>${(r.metrics.wer*100).toFixed(2)}%</td><td>${r.metrics.substitutions} / ${r.metrics.deletions} / ${r.metrics.insertions}</td><td>${r.metrics.reference_words}<small>边界不确定句含 ${r.boundary_uncertain_reference_words} 词</small></td><td>${Number(r.latency_seconds).toFixed(2)} 秒</td></tr>`).join('')}</tbody></table></div>`;
}
function renderResults(){renderContextLadder();renderSmokeResults();renderTranscriptionResults();renderSingleContextResults();const condition=$('#result-condition').value;const runs=getLatestRuns(condition);$('#results-note').textContent=runs.length?`当前条件已记录 ${runs.length} 个模型 × 样例结果。下表仅统计本题集，每个组合展示最新 attempt。`:'本题集尚未运行模型。结果区已准备好：接入真实结果后，这里会显示逐题选择、正确率、耗时和输入声道处理方式。';
if(resultData.transcription_evaluation)$('#results-note').textContent+=` Muse 当前条件已完成 ${resultData.transcription_evaluation.conditions[condition].completed} 条转录，WER 单独统计。`;
$('#model-table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>模型</th><th>状态</th><th>已运行样例</th><th>有效答题 / 正确数</th><th>准确率 / WER</th><th>输入说明</th></tr></thead><tbody>${resultData.models.map(m=>{const asr=resultData.transcription_evaluation;if(asr&&m.id===asr.model_id){const a=asr.conditions[condition];return `<tr><td>${esc(m.name)}<small>${esc(m.kind)}</small></td><td><span class="pill">转录完成</span></td><td>${a.completed} / 10</td><td>不适用（仅转录）</td><td>WER ${(a.wer*100).toFixed(2)}%<small>越低越好 · 不计选择题准确率</small></td><td>downmixed_mono</td></tr>`;}const rs=runs.filter(r=>r.model_id===m.id),valid=rs.flatMap(r=>r.questions).filter(q=>q.prediction!==null),n=valid.length,c=valid.filter(q=>q.correct).length;return `<tr><td>${esc(m.name)}<small>${esc(m.kind)}</small></td><td><span class="pill">${rs.length?'已记录 '+rs.length+' 条':'未运行'}</span></td><td>${rs.length} / 10</td><td>${rs.length?`${n} / 50 题有效 · ${c} 正确`:'—'}</td><td>${rs.length===10?(n?`${c} / 50 · ${Math.round(c/50*100)}%`:'无有效答案'):rs.length?'进行中':'—'}</td><td>${rs.length?esc([...new Set(rs.map(r=>r.channel_handling))].join(' / ')):'待核验'}</td></tr>`;}).join('')}</tbody></table></div>`;
if(!$('#result-model').options.length){$('#result-model').innerHTML=resultData.models.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('');$('#result-sample').innerHTML=data.samples.map(s=>`<option value="${s.id}">${s.id}</option>`).join('');$('#result-model').onchange=renderQuestionResults;$('#result-sample').onchange=renderQuestionResults;}renderQuestionResults();}
function renderQuestionResults(){const asr=resultData.transcription_evaluation;if(asr&&$('#result-model').value===asr.model_id){const row=asr.runs.find(r=>r.condition===$('#result-condition').value&&r.sample_id===$('#result-sample').value);if(!row){$('#question-results').innerHTML='<p class="fineprint">此样例尚无转录结果。</p>';return;}const m=row.metrics;$('#question-results').innerHTML=`<p><strong>${esc(row.sample_id)} · 转录完成 · 诊断 WER ${(m.wer*100).toFixed(2)}%</strong></p><p class="fineprint">Muse 仅做转录，未进行选择题作答。${esc(row.channel_handling)} · ${Number(row.latency_seconds).toFixed(2)} 秒</p><div class="table-wrap"><table><thead><tr><th>参考词数</th><th>输出词数</th><th>替换</th><th>删除</th><th>插入</th></tr></thead><tbody><tr><td>${m.reference_words}</td><td>${m.hypothesis_words}</td><td>${m.substitutions}</td><td>${m.deletions}</td><td>${m.insertions}</td></tr></tbody></table></div><p class="fineprint">${esc(asr.note)} 边界不确定句包含 ${row.boundary_uncertain_reference_words} 个参考词。</p>`;return;}const r=getLatestRuns($('#result-condition').value).find(r=>r.model_id===$('#result-model').value&&r.sample_id===$('#result-sample').value);if(!r){$('#question-results').innerHTML='<div class="empty"><strong>等待该模型与样例的答题结果</strong><p>这里将显示五道题的模型选择、参考答案、判定与运行信息。</p></div>';return;}$('#question-results').innerHTML=`<p class="fineprint">${esc(r.created_at)} · ${esc(r.status)} · ${r.latency_seconds??'—'} 秒 · ${esc(r.channel_handling)}</p><div class="table-wrap"><table><thead><tr><th>题目</th><th>模型选择</th><th>参考答案</th><th>判定</th></tr></thead><tbody>${r.questions.map(q=>`<tr><td>${esc(q.id)}</td><td>${esc(q.prediction??'无法解析')}</td><td>${esc(q.gold)}</td><td>${q.prediction===null?'未评分':q.correct?'正确':'错误'}</td></tr>`).join('')}</tbody></table></div>${r.error_message?`<p class="fineprint">${esc(r.error_message)}</p>`:''}`;}
async function init(){try{[data,meta,resultData,listeningData]=await Promise.all([loadJSON('questions.json'),loadJSON('provenance.json'),loadJSON('results.json'),loadJSON('listening-audio.json')]);$('#result-condition').onchange=renderResults;window.addEventListener('hashchange',route);route();}catch(e){$('#sample-content').innerHTML=`<div class="error">页面数据未能载入。请刷新重试。<br><small>${esc(e.message)}</small></div>`;}}
init();

function renderSingleContextResults(){
const evaluation=resultData.single_context_ablation,box=$('#single-context-results');box.hidden=!evaluation;if(!evaluation)return;
const condition=$('#result-condition').value,names=new Map(resultData.models.map(m=>[m.id,m.name]));
const rows=evaluation.models.map(m=>({m,d:m.groups.find(g=>g.condition===condition&&g.arm==='dual'),s:m.groups.find(g=>g.condition===condition&&g.arm==='single'),p:m.pairs.find(p=>p.condition===condition)}));
const mark=r=>r.correct?'正确':r.answered_all?'错误':'未答／无效';
const prediction=r=>Object.entries(r.subanswers).map(([k,v])=>(k.endsWith('-A')?'A组 ':k.endsWith('-B')?'B组 ':'')+(v??'—')+((k.endsWith('-A')||k.endsWith('-B'))?(r.subanswer_correct[k]?'（对）':'（错）'):'')).join('；');
box.innerHTML=`<p class="eyebrow">SINGLE VS DUAL CONTEXT · MATCHED PROMPTS</p><h3>单 context 补充实验</h3><p class="fineprint">${esc(evaluation.note)}</p><p><strong>${condition==='spatial'?'空间版':'同位置对照'}</strong> · 原混音20/20逐点重建一致 · 单context音频40条</p><div class="table-wrap"><table><thead><tr><th>模型</th><th>双 context</th><th>单 context</th><th>净变化</th><th>配对变化</th><th>输入</th></tr></thead><tbody>${rows.map(({m,d,s,p})=>`<tr><td>${esc(names.get(m.model_id)??m.model_id)}<small>${m.protocol?.format==='single_question'?'逐题独立 · 240次调用':'按来源分组 · 80次调用'}</small></td><td>${m.status==='partial'?'未完成 · ':''}${d.correct}/50<small>${m.status==='partial'?d.completed_calls+'/20组完成 · ':''}${d.valid_subanswers}/60 子答案有效</small></td><td>${m.status==='partial'?'未完成 · ':''}${s.correct}/50<small>${m.status==='partial'?s.completed_calls+'/20组完成 · ':''}${s.valid_subanswers}/60 子答案有效</small></td><td>${m.status==='partial'?'—（未完成）':(p.single_minus_dual>0?'+':'')+p.single_minus_dual+' 题'}</td><td>${m.status==='partial'?'余额不足 · 不作完整配对比较':`改善 ${p.single_only_correct} · 退步 ${p.dual_only_correct}<small>同对 ${p.both_correct} · 同错 ${p.both_wrong}</small>`}</td><td>${m.channel_handling==='native_48k_stereo'?'原生双声道':m.channel_handling==='ffmpeg_mono16k'?'FFmpeg单声道16k':'L/R均值转单声道'}</td></tr>`).join('')}</tbody></table></div><p class="fineprint">每个分数分母均为50；格式无效或缺失计错。交互协议因模型而异，主要比较同一模型的单／双context。人数接受整数或纯数字字符串。单声道结果不能作为保留双耳空间线索的证据。10个片段来自少量原会话，差值仅作诊断。</p>${rows.map(({m,d,s})=>`<details class="evidence"><summary>${esc(names.get(m.model_id)??m.model_id)} · 展开50题单／双context对照${m.status==='partial'?'（未答包含未运行项）':''}</summary><div class="table-wrap"><table><thead><tr><th>原题</th><th>双context答案</th><th>判定</th><th>单context答案</th><th>判定</th></tr></thead><tbody>${d.rows.map((r,i)=>{const peer=s.rows.find(q=>q.id===r.id);return `<tr><td>${esc(r.id)}${r.id.endsWith('-Q5')?'<small>两个人数均正确才得分</small>':''}</td><td>${esc(prediction(r))}</td><td>${mark(r)}</td><td>${esc(prediction(peer))}</td><td>${mark(peer)}</td></tr>`;}).join('')}</tbody></table></div></details>`).join('')}${renderSingleContextLive(evaluation.models.find(m=>m.behavior)?.behavior,condition)}${renderSingleContextWER(evaluation.transcription,condition)}`;
}

function renderSingleContextWER(t,condition){
if(!t)return '';const gs=t.groups.filter(g=>g.condition===condition),rs=t.rows.filter(r=>r.condition===condition),pct=v=>(100*v).toFixed(2)+'%';
return `<h3>Muse · 单 context 转录对照</h3><p class="fineprint">${esc(t.note)}</p><div class="table-wrap"><table><thead><tr><th>输入</th><th>完成音频</th><th>参考词</th><th>替换</th><th>删除</th><th>插入</th><th>WER ↓</th></tr></thead><tbody>${gs.map(g=>`<tr><td>${g.arm==='dual'?'双 context':'单 context A+B汇总'}</td><td>${g.completed_calls}/${g.planned_calls}</td><td>${g.reference_words}</td><td>${g.substitutions}</td><td>${g.deletions}</td><td>${g.insertions}</td><td>${pct(g.wer)}</td></tr>`).join('')}</tbody></table></div><details class="evidence"><summary>展开每段音频的转录错误统计</summary><div class="table-wrap"><table><thead><tr><th>片段</th><th>输入</th><th>参考词</th><th>S / D / I</th><th>WER ↓</th><th>边界不确定词</th></tr></thead><tbody>${rs.map(r=>`<tr><td>${esc(r.sample_id)}</td><td>${r.arm==='dual'?'双context':'单context '+r.target_context}</td><td>${r.metrics.reference_words}</td><td>${r.metrics.substitutions} / ${r.metrics.deletions} / ${r.metrics.insertions}</td><td>${pct(r.metrics.wer)}</td><td>${r.boundary_uncertain_reference_words}</td></tr>`).join('')}</tbody></table></div></details>`;
}

function renderSingleContextLive(b,condition){
if(!b)return '';const rows=b.rows.filter(r=>r.task_id.includes('-'+condition+'-'));
return `<details class="evidence"><summary>GPT-Live · 会话行为与插话记录</summary><p class="fineprint">全条件 ${b.completed}/${b.calls} 技术完成；当前${b.credit_blocked_calls}次因余额不足未能开始；另有${b.historical_credit_rejections}次历史余额拒绝及${b.excluded_preflight_calls}次实现问题预检留档；${b.calls_with_early_output}次提前输出，其中${b.calls_with_premature_answers}次含可解析的提前答案，${b.calls_without_post_audio_output}次完整音频后无文字输出，${b.calls_with_valid_answers}次有可解析答案。主评分仅计完整60秒之后的编号答案。原生事件、转录和输出音频完整私有留档。</p><div class="table-wrap"><table><thead><tr><th>会话</th><th>提前输出</th><th>结束后输出</th><th>有效答案</th><th>技术状态</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.task_id)}</td><td>${r.early_output?'有 · '+r.early_transcript_characters+'字符 / '+r.early_valid_answers+'个提前答案':'无'}</td><td>${r.post_audio_output?'有 · '+r.post_audio_transcript_characters+'字符':'无'}</td><td>${r.valid_answers}</td><td>${r.status==='completed'?'完成':'余额不足 · 未开始'}</td></tr>`).join('')}</tbody></table></div></details>`;
}

let ladderScene=1,ladderModel='',ladderFilter='all',ladderSample='all';
const ladderArms={1:'single',2:'dual',3:'triple',4:'quadruple'};
const ladderDescriptions={1:'只播放问题所属的 A 或 B',2:'会议 A + 晚餐 B',3:'A + B + 一路朗读干扰',4:'A + B + 两路朗读干扰'};
function ladderGroup(model,k,condition){return model.groups.find(g=>g.context_count===k&&g.condition===condition);}
function renderContextLadder(){
 const box=$('#context-ladder-results'),e=resultData.context_ladder;box.hidden=!e;if(!e)return;
 const condition=$('#result-condition').value,names=new Map(resultData.models.map(m=>[m.id,m.name]));
 if(!e.models.some(m=>m.model_id===ladderModel))ladderModel=e.models[0].model_id;
 const name=m=>names.get(m.model_id)??m.model_id;
 box.innerHTML=`<div class="panel"><p class="eyebrow">SAME 50 QUESTIONS · 1–4 CONTEXTS</p><h2>不同 context 数量，总体表现</h2><p class="fineprint">${esc(e.note)}</p><div class="ladder-legend">${[1,2,3,4].map(k=>`<span><i class="ladder-color k${k}"></i>${k} context</span>`).join('')}</div><p class="fineprint">${condition==='spatial'?'空间版':'同位置对照'} · 正确率，越高越好 · 每根柱均为同一组 50 题</p><div class="ladder-chart" aria-label="七个模型在一至四 context 下的正确率柱状图">${e.models.map(m=>`<div class="ladder-model"><strong>${esc(name(m))}</strong><div class="ladder-bars">${[1,2,3,4].map(k=>{const g=ladderGroup(m,k,condition),done=g?.attempted_calls===20;return `<div class="ladder-bar-row"><span>${k} context</span><div class="ladder-track"><div class="ladder-fill k${k}" style="width:${done?g.correct*2:0}%"></div></div><b>${done?g.correct+'/50 · '+g.correct*2+'%':'待完成'}</b></div>`;}).join('')}</div></div>`).join('')}</div><p class="fineprint">总分包含未答、格式无效和技术失败项，均计错。单声道模型的差值不能直接解释为双耳空间能力。原 1/2 context 结果保留；新增 C/D 为不同说话人的英语朗读，原 A/B 声源、问题和答案不变。</p></div>
 <div class="panel"><p class="eyebrow">FOUR SCENARIOS</p><h2>按 context 场景查看</h2><div class="ladder-scenes">${[1,2,3,4].map(k=>`<button class="ladder-scene ${ladderScene===k?'selected':''}" data-context="${k}" aria-pressed="${ladderScene===k}"><strong>${k} context</strong><small>${ladderDescriptions[k]}</small></button>`).join('')}</div><div id="ladder-scene-summary"></div></div>
 <div class="panel"><p class="eyebrow">QUESTION BY QUESTION</p><h2>每道题的答案与对错</h2><div class="filters"><label>场景 <select id="ladder-detail-context">${[1,2,3,4].map(k=>`<option value="${k}" ${ladderScene===k?'selected':''}>${k} context</option>`).join('')}</select></label><label>模型 <select id="ladder-detail-model">${e.models.map(m=>`<option value="${esc(m.model_id)}" ${m.model_id===ladderModel?'selected':''}>${esc(name(m))}</option>`).join('')}</select></label><label>样例 <select id="ladder-detail-sample"><option value="all">全部 10 段</option>${data.samples.map(s=>`<option value="${s.id}" ${s.id===ladderSample?'selected':''}>${s.id}</option>`).join('')}</select></label><label>判定 <select id="ladder-detail-filter">${[['all','全部'],['correct','正确'],['wrong','错误（含未答）'],['missing','未答／无效']].map(([v,l])=>`<option value="${v}" ${ladderFilter===v?'selected':''}>${l}</option>`).join('')}</select></label></div><div id="ladder-question-board" aria-live="polite"></div></div><div id="ladder-live-behavior"></div><div id="ladder-muse-results"></div>`;
 box.querySelectorAll('[data-context]').forEach(b=>b.onclick=()=>{ladderScene=Number(b.dataset.context);renderContextLadder();});
 $('#ladder-detail-context').onchange=ev=>{ladderScene=Number(ev.target.value);renderContextLadder();};
 $('#ladder-detail-model').onchange=ev=>{ladderModel=ev.target.value;renderLadderQuestions();};
 $('#ladder-detail-sample').onchange=ev=>{ladderSample=ev.target.value;renderLadderQuestions();};
 $('#ladder-detail-filter').onchange=ev=>{ladderFilter=ev.target.value;renderLadderQuestions();};
 $('#ladder-scene-summary').innerHTML=`<h3>${ladderScene} context · ${condition==='spatial'?'空间版':'同位置对照'}</h3><p class="fineprint">${ladderDescriptions[ladderScene]}。人数题始终只评 A/B，两个子答案均正确才得 1 分。每场景有 20 个 A/B 任务组；Kimi/Moshi 逐题调用，其余按来源分组，技术完成不代表答对。</p><div class="table-wrap"><table><thead><tr><th>模型</th><th>正确 / 50</th><th>错误（含未答）</th><th>有效子答案 / 60</th><th>技术完成组 / 20</th><th>输入方式</th></tr></thead><tbody>${e.models.map(m=>{const g=ladderGroup(m,ladderScene,condition);return `<tr><td>${esc(name(m))}</td><td>${g?.attempted_calls===20?g.correct:'待完成'}</td><td>${g?.attempted_calls===20?50-g.correct:'—'}</td><td>${g?.valid_subanswers??0} / 60</td><td>${g?.completed_calls??0} / 20</td><td>${m.channel_handling==='native_48k_stereo'?'双声道输入':'单声道输入'}</td></tr>`;}).join('')}</tbody></table></div>`;
 renderLadderQuestions();renderLadderLive(e,condition);renderLadderMuse(e,condition);
}
function renderLadderQuestions(){
 const e=resultData.context_ladder,condition=$('#result-condition').value,m=e.models.find(m=>m.model_id===ladderModel),g=ladderGroup(m,ladderScene,condition),box=$('#ladder-question-board');
 if(!g||g.attempted_calls!==20){box.innerHTML='<p class="fineprint">该场景尚未完成，完成后展示逐题判定。</p>';return;}
 const qs=new Map(data.samples.flatMap(s=>s.questions).map(q=>[q.id,q])),gold=e.gold;
 const rows=g.rows.filter(r=>(ladderSample==='all'||r.id.startsWith(ladderSample+'-'))&&(ladderFilter==='all'||ladderFilter==='correct'&&r.correct||ladderFilter==='wrong'&&!r.correct||ladderFilter==='missing'&&!r.answered_all));
 const prediction=r=>Object.entries(r.subanswers).map(([id,v])=>`${id.endsWith('-A')?'A组 ':id.endsWith('-B')?'B组 ':''}${v??'—'}${r.id.endsWith('-Q5')?'（'+(v==null?'未答':r.subanswer_correct[id]?'对':'错')+'）':''}`).join('；');
 box.innerHTML=`<p class="fineprint">${ladderScene} context · ${condition==='spatial'?'空间版':'同位置对照'} · 显示 ${rows.length} / 50 题；正确 ${g.correct}，错误 ${50-g.correct}。未答／无效属于错误。题号链接打开对应 context 的试听与原题；单 context 人数题需分别听 A/B。</p>${rows.length?`<div class="table-wrap"><table class="ladder-detail-table"><thead><tr><th>题目</th><th>模型答案</th><th>正确答案</th><th>判定</th></tr></thead><tbody>${rows.map(r=>{const q=qs.get(r.id),isCount=r.id.endsWith('-Q5'),truth=gold[r.id];return `<tr><td><a href="#${listenPath(r.id.split('-')[0],ladderScene===1?(r.id.endsWith('-Q4')?'singleB':'singleA'):ladderArms[ladderScene])}">${esc(r.id)}</a><details><summary>${esc(types[q.type])} · 查看题目</summary><p>${esc(q.question)}</p>${isCount?'<p>本轮拆分为 A、B 两个独立人数子问，均正确才计分。</p>':`<ol type="A">${q.options.map(o=>`<li>${esc(o)}</li>`).join('')}</ol>`}</details></td><td>${esc(prediction(r))}</td><td>${esc(isCount?'A组 '+truth.A+'；B组 '+truth.B:truth)}</td><td><span class="ladder-verdict ${r.correct?'correct':r.answered_all?'wrong':'missing'}">${r.correct?'正确':r.answered_all?'错误':'未答／无效'}</span></td></tr>`;}).join('')}</tbody></table></div>`:'<p>当前筛选下没有题目。</p>'}`;
}
function renderLadderLive(e,condition){
 const model=e.models.find(m=>m.model_id==='gpt-live-1'),rows=(model?.behavior_rows??[]).filter(r=>r.task_id.includes('-'+condition+'-')&&r.context_count===ladderScene),box=$('#ladder-live-behavior');
 if(!rows.length){box.innerHTML='';return;}
 box.innerHTML=`<details class="panel"><summary>GPT-Live · ${ladderScene} context 会话与插话记录</summary><p class="fineprint">${rows.filter(r=>r.status==='completed').length}/${rows.length} 会话技术完成；${rows.filter(r=>r.early_output).length} 个会话有提前输出，${rows.filter(r=>r.early_valid_answers>0).length} 个会话含提前答案。主评分只计完整音频之后的编号答案。提前输出包含回应与插话，按原生转录事件统计；首次输出时间从会话请求开始计。${rows.some(r=>r.failure_reason==='finalization_timeout')?' 本场景有会话在完整音频发送后等待结束确认超时，保留为技术失败、不重试；对应 usage 尚未最终确认。':''}</p><div class="table-wrap"><table><thead><tr><th>会话</th><th>提前输出</th><th>结束后输出</th><th>有效答案</th><th>技术状态</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.task_id)}</td><td>${r.early_output?r.early_transcript_characters+' 字符 / '+r.early_valid_answers+' 个提前答案 · 首次 '+(r.first_early_output_seconds==null?'—':r.first_early_output_seconds.toFixed(1)+'s'):'无'}</td><td>${r.post_audio_output?r.post_audio_transcript_characters+' 字符 · 首次 '+(r.first_post_audio_output_seconds==null?'—':r.first_post_audio_output_seconds.toFixed(1)+'s'):'无'}</td><td>${r.valid_answers}</td><td>${r.status==='completed'?'完成':r.failure_reason==='finalization_timeout'?'结束确认超时':'失败'}</td></tr>`).join('')}</tbody></table></div></details>`;
}
function renderLadderMuse(e,condition){
 const t=e.transcription,box=$('#ladder-muse-results');if(!t){box.innerHTML='';return;}
 const groups=t.groups.filter(g=>g.condition===condition).sort((a,b)=>a.context_count-b.context_count),rows=t.rows.filter(r=>r.condition===condition&&r.context_count===ladderScene);
 box.innerHTML=`<div class="panel"><h3>Muse · 全来源转录 WER</h3><p class="fineprint">${esc(t.note)}</p><div class="table-wrap"><table><thead><tr><th>场景</th><th>完成音频</th><th>参考词</th><th>替换 / 删除 / 插入</th><th>WER ↓</th></tr></thead><tbody>${groups.map(g=>`<tr><td>${g.context_count} context</td><td>${g.completed_calls}/${g.planned_calls}</td><td>${g.reference_words}</td><td>${g.substitutions} / ${g.deletions} / ${g.insertions}</td><td>${(g.wer*100).toFixed(2)}%</td></tr>`).join('')}</tbody></table></div><details><summary>${ladderScene} context · 每段音频错误统计</summary><div class="table-wrap"><table><thead><tr><th>样例</th><th>来源</th><th>参考词</th><th>S / D / I</th><th>WER ↓</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.sample_id)}</td><td>${r.target_context==='A'||r.target_context==='B'?r.target_context:'全部来源'}</td><td>${r.metrics.reference_words}</td><td>${r.metrics.substitutions} / ${r.metrics.deletions} / ${r.metrics.insertions}</td><td>${(r.metrics.wer*100).toFixed(2)}%</td></tr>`).join('')}</tbody></table></div></details></div>`;
}
