'use strict';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const types={time_localization:'时间定位',speaker_content:'谁说了什么',content_context_A:'会议内容',content_context_B:'晚餐内容',speaker_counts:'各组人数'};
let data,meta,resultData,answers=null,current='SC001';
const selections=new Map(),submitted=new Set();
async function loadJSON(path){const r=await fetch(path);if(!r.ok)throw new Error(`${path}: HTTP ${r.status}`);return r.json();}
const sample=()=>data.samples.find(s=>s.id===current);
function route(){const raw=location.hash.slice(1);const parts=raw.split('/');const view=['results','about'].includes(parts[0])?parts[0]:'listen';if(parts[1]&&data.samples.some(s=>s.id===parts[1]))current=parts[1];for(const v of ['listen','results','about']){$(`#${v}-view`).hidden=v!==view;$(`#nav-${v}`).classList.toggle('active',v===view);}if(view==='listen')renderSample();if(view==='results')renderResults();}
function renderList(){$('#sample-list').innerHTML=data.samples.map((s,i)=>`<button class="sample-button ${s.id===current?'selected':''}" data-sample="${s.id}" aria-pressed="${s.id===current}"><span class="sample-number">${String(i+1).padStart(2,'0')}</span><span class="sample-name">${esc(meta.samples[i].title)}<small>${s.id} · 60 秒</small></span></button>`).join('');$('#sample-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{location.hash=`listen/${b.dataset.sample}`;});}
function roomSVG(m){let s='<svg class="room" viewBox="0 0 240 170" role="img" aria-label="虚拟房间俯视图：蓝色会议组 A，橙色晚餐组 B，听者面向前方"><defs><pattern id="grid" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M22 0H0V22" fill="none" stroke="#e6ecf2" stroke-width=".5"/></pattern></defs><rect x="15" y="12" width="210" height="145" rx="5" fill="url(#grid)" stroke="#c9d6e3"/><path d="M120 105L113 119H127Z" fill="#283f52"/><text x="105" y="139" fill="#60727c" font-size="9">听者</text>';
for(const [ctx,p] of Object.entries(m.room.source_xyz_m)){const x=15+p[0]/6*210,y=157-p[1]/5*145,color=ctx==='A'?'#295eda':'#b7683b';s+=`<path d="M120 112L${x} ${y}" stroke="${color}" opacity=".35" stroke-dasharray="3 3"/><circle cx="${x}" cy="${y}" r="14" fill="${color}" opacity=".1"/><circle cx="${x}" cy="${y}" r="6" fill="${color}"/><text x="${x-13}" y="${y-20}" font-size="10" fill="${color}">组 ${ctx}</text>`;}return s+'</svg>';}
function renderSample(){renderList();const s=sample(),m=meta.samples.find(x=>x.id===s.id);const done=submitted.has(current);$('#sample-content').innerHTML=`<section class="panel"><div class="sample-header"><div><span class="sample-id">${s.id} / TWO CONTEXTS</span><h2>${esc(m.title)}</h2><div class="tags"><span class="tag">60 秒</span><span class="tag">48 kHz · 双声道</span><span class="tag">5 道题</span></div></div><button class="share-btn" id="share">分享此样例 ↗</button></div><div class="room-row">${roomSVG(m)}<div class="room-copy"><p><span class="legend-a">● 会议组 A</span>　NOTSOFAR</p><p><span class="legend-b">● 晚餐组 B</span>　CHiME-6</p><p>两个组级声源，左右方位 ${Math.abs(m.room.azimuth_deg.A)}°。<br>对照版两组都位于正前方。</p></div></div><div class="players">${[['spatial','空间版','两个不同方位 · 建议耳机'],['colocated','同位置对照','同一正前方 · 音量匹配']].map(([c,title,sub])=>`<div class="player"><h3>${title}</h3><p>${sub}</p><audio controls preload="none" src="${esc(s.audio[c])}" aria-label="${s.id} ${title}"></audio><a href="${esc(s.audio[c])}" download>↓ 下载原始 WAV</a></div>`).join('')}</div></section><section class="panel"><div class="questions-top"><h3>听完，试着回答</h3><small>每题四选一 · 两版共用题目</small></div><form id="quiz">${s.questions.map((q,i)=>`<section class="question" id="${q.id}"><div class="q-meta"><span>QUESTION ${i+1} / 5</span><span class="q-type">${types[q.type]}</span></div><p class="q-text">${esc(q.question)}</p><div class="options">${q.options.map((o,j)=>`<label class="option"><input type="radio" name="${q.id}" value="${j}" ${selections.get(q.id)===j?'checked':''}><span class="letter">${'ABCD'[j]}</span><span>${esc(o)}</span></label>`).join('')}</div><div class="answer-slot"></div></section>`).join('')}<div class="quiz-actions"><button class="primary" type="submit">检查我的答案</button><button class="secondary" id="reveal" type="button">查看答案与证据</button><span class="score" id="score" role="status"></span></div></form><p class="note">作答仅在当前浏览器页面中保留。查看答案后仍可重新选择并评分。</p></section>`;
$('#share').onclick=async()=>{const url=new URL(location.href);url.hash=`listen/${current}`;try{await navigator.clipboard.writeText(url.href);$('#share').textContent='链接已复制';}catch{$('#share').textContent='复制地址栏即可分享';}};
$('#quiz').onchange=e=>{if(e.target.type==='radio')selections.set(e.target.name,Number(e.target.value));};
$('#quiz').onsubmit=async e=>{e.preventDefault();try{await showAnswers(true);}catch{$('#score').textContent='答案加载失败，请重试。';}};
$('#reveal').onclick=async()=>{try{await showAnswers(false);}catch{$('#score').textContent='答案加载失败，请重试。';}};
document.querySelectorAll('audio').forEach(a=>a.onplay=()=>document.querySelectorAll('audio').forEach(b=>{if(a!==b)b.pause();}));
if(done&&answers)showAnswers(true);
}
async function showAnswers(score){if(!answers)answers=await loadJSON('answers.json');const s=sample();const g=answers.samples.find(x=>x.id===s.id);let correct=0,answered=0;for(const a of g.answers){const q=document.getElementById(a.id),selected=selections.get(a.id);if(selected!==undefined){answered++;if(selected===a.answer_index)correct++;}q.querySelectorAll('.option').forEach((label,i)=>{label.classList.toggle('correct',i===a.answer_index);label.classList.toggle('wrong',score&&i===selected&&i!==a.answer_index);});q.querySelector('.answer-slot').innerHTML=`<details class="evidence"><summary>答案 ${a.answer} · 展开逐句证据</summary>${a.evidence.map(e=>`<p><small>${esc(e.row_id)} · ${Number(e.start).toFixed(2)}–${Number(e.end).toFixed(2)} 秒 · ${esc(e.speaker)}</small><br>${esc(e.clean_text)}</p>`).join('')}</details>`;}if(score){submitted.add(current);$('#score').textContent=`答对 ${correct} / 5 · 已作答 ${answered} / 5${answered<5?'（未答题尚未选择）':''}`;}else $('#score').textContent='已显示参考答案。';}
function getLatestRuns(condition){const latest=new Map();for(const r of [...resultData.runs].sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at))){if(r.condition===condition)latest.set(r.model_id+'|'+r.sample_id,r);}return [...latest.values()];}
function renderSmokeResults(){const rows=resultData.smoke_runs??[],names=new Map(resultData.models.map(m=>[m.id,m.name])),kinds={hear_voice_attribution:'HEAR · 声音归属',notsofar_native_stream:'NOTSOFAR · 原生流式',notsofar_transcription:'NOTSOFAR · 转录',spatial_transcription:'SC001 · 空间版转录'},states={pass:'通过',fail:'失败',blocked:'受阻'};$('#smoke-table').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>模型</th><th>样本</th><th>终态</th><th>结果摘要</th><th>耗时</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(names.get(r.model_id)??r.model_id)}</td><td>${esc(kinds[r.sample_kind]??r.sample_kind)}<small>${Number(r.duration_seconds).toFixed(2)} 秒</small></td><td><span class="pill">${esc(states[r.status]??r.status)}</span></td><td>${esc(r.summary)}</td><td>${r.latency_seconds==null?'—':Number(r.latency_seconds).toFixed(2)+' 秒'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="fineprint">尚无已归档的单样本链路结果。</p>';
const protocols=resultData.model_protocols??[],box=$('#model-protocols');box.hidden=!protocols.length;if(protocols.length)box.innerHTML=`<h3>评测协议</h3><p class="fineprint">一次回答 5 题与每次回答 1 题的协议不同；Muse 每次转录一条音频，仅计算 WER。分数与耗时需结合调用方式解读。</p><div class="table-wrap"><table><thead><tr><th>模型</th><th>每次题数</th><th>模型调用数</th><th>说明</th></tr></thead><tbody>${protocols.map(r=>`<tr><td>${esc(names.get(r.model_id)??r.model_id)}</td><td>${r.questions_per_call??'不适用'}</td><td>${r.inference_calls??'—'}</td><td>${esc(r.prompt_note)}</td></tr>`).join('')}</tbody></table></div>`;}
function renderTranscriptionResults(){
const evaluation=resultData.transcription_evaluation,box=$('#transcription-results');box.hidden=!evaluation;if(!evaluation)return;
const condition=$('#result-condition').value,totals=evaluation.conditions[condition],rows=evaluation.runs.filter(r=>r.condition===condition);
box.innerHTML=`<h3>Muse · 完整标注转录 WER</h3><p>全部 20 条转录已完成 · 20 分钟音频 · 费用 $${Number(evaluation.cost_usd).toFixed(2)}</p><p class="fineprint">${esc(evaluation.note)}</p><p><strong>${condition==='spatial'?'空间版':'同位置对照'} WER ${(totals.wer*100).toFixed(2)}%</strong> · ${totals.completed}/10 条 · 参考 ${totals.reference_words} 词 · 替换 ${totals.substitutions} / 删除 ${totals.deletions} / 插入 ${totals.insertions}</p><div class="table-wrap"><table><thead><tr><th>样例</th><th>WER</th><th>替换 / 删除 / 插入</th><th>参考词数</th><th>耗时</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.sample_id)}</td><td>${(r.metrics.wer*100).toFixed(2)}%</td><td>${r.metrics.substitutions} / ${r.metrics.deletions} / ${r.metrics.insertions}</td><td>${r.metrics.reference_words}<small>边界不确定句含 ${r.boundary_uncertain_reference_words} 词</small></td><td>${Number(r.latency_seconds).toFixed(2)} 秒</td></tr>`).join('')}</tbody></table></div>`;
}
function renderResults(){renderSmokeResults();renderTranscriptionResults();const condition=$('#result-condition').value;const runs=getLatestRuns(condition);$('#results-note').textContent=runs.length?`当前条件已记录 ${runs.length} 个模型 × 样例结果。下表仅统计本题集，每个组合展示最新 attempt。`:'本题集尚未运行模型。结果区已准备好：接入真实结果后，这里会显示逐题选择、正确率、耗时和输入声道处理方式。';
if(resultData.transcription_evaluation)$('#results-note').textContent+=` Muse 当前条件已完成 ${resultData.transcription_evaluation.conditions[condition].completed} 条转录，WER 单独统计。`;
$('#model-table').innerHTML=`<div class="table-wrap"><table><thead><tr><th>模型</th><th>状态</th><th>已运行样例</th><th>有效答题 / 正确数</th><th>准确率 / WER</th><th>输入说明</th></tr></thead><tbody>${resultData.models.map(m=>{const asr=resultData.transcription_evaluation;if(asr&&m.id===asr.model_id){const a=asr.conditions[condition];return `<tr><td>${esc(m.name)}<small>${esc(m.kind)}</small></td><td><span class="pill">转录完成</span></td><td>${a.completed} / 10</td><td>不适用（仅转录）</td><td>WER ${(a.wer*100).toFixed(2)}%<small>越低越好 · 不计选择题准确率</small></td><td>downmixed_mono</td></tr>`;}const rs=runs.filter(r=>r.model_id===m.id),valid=rs.flatMap(r=>r.questions).filter(q=>q.prediction!==null),n=valid.length,c=valid.filter(q=>q.correct).length;return `<tr><td>${esc(m.name)}<small>${esc(m.kind)}</small></td><td><span class="pill">${rs.length?'已记录 '+rs.length+' 条':'未运行'}</span></td><td>${rs.length} / 10</td><td>${rs.length?`${n} / 50 题有效 · ${c} 正确`:'—'}</td><td>${rs.length===10?(n?`${c} / 50 · ${Math.round(c/50*100)}%`:'无有效答案'):rs.length?'进行中':'—'}</td><td>${rs.length?esc([...new Set(rs.map(r=>r.channel_handling))].join(' / ')):'待核验'}</td></tr>`;}).join('')}</tbody></table></div>`;
if(!$('#result-model').options.length){$('#result-model').innerHTML=resultData.models.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('');$('#result-sample').innerHTML=data.samples.map(s=>`<option value="${s.id}">${s.id}</option>`).join('');$('#result-model').onchange=renderQuestionResults;$('#result-sample').onchange=renderQuestionResults;}renderQuestionResults();}
function renderQuestionResults(){const asr=resultData.transcription_evaluation;if(asr&&$('#result-model').value===asr.model_id){const row=asr.runs.find(r=>r.condition===$('#result-condition').value&&r.sample_id===$('#result-sample').value);if(!row){$('#question-results').innerHTML='<p class="fineprint">此样例尚无转录结果。</p>';return;}const m=row.metrics;$('#question-results').innerHTML=`<p><strong>${esc(row.sample_id)} · 转录完成 · 诊断 WER ${(m.wer*100).toFixed(2)}%</strong></p><p class="fineprint">Muse 仅做转录，未进行选择题作答。${esc(row.channel_handling)} · ${Number(row.latency_seconds).toFixed(2)} 秒</p><div class="table-wrap"><table><thead><tr><th>参考词数</th><th>输出词数</th><th>替换</th><th>删除</th><th>插入</th></tr></thead><tbody><tr><td>${m.reference_words}</td><td>${m.hypothesis_words}</td><td>${m.substitutions}</td><td>${m.deletions}</td><td>${m.insertions}</td></tr></tbody></table></div><p class="fineprint">${esc(asr.note)} 边界不确定句包含 ${row.boundary_uncertain_reference_words} 个参考词。</p>`;return;}const r=getLatestRuns($('#result-condition').value).find(r=>r.model_id===$('#result-model').value&&r.sample_id===$('#result-sample').value);if(!r){$('#question-results').innerHTML='<div class="empty"><strong>等待该模型与样例的答题结果</strong><p>这里将显示五道题的模型选择、参考答案、判定与运行信息。</p></div>';return;}$('#question-results').innerHTML=`<p class="fineprint">${esc(r.created_at)} · ${esc(r.status)} · ${r.latency_seconds??'—'} 秒 · ${esc(r.channel_handling)}</p><div class="table-wrap"><table><thead><tr><th>题目</th><th>模型选择</th><th>参考答案</th><th>判定</th></tr></thead><tbody>${r.questions.map(q=>`<tr><td>${esc(q.id)}</td><td>${esc(q.prediction??'无法解析')}</td><td>${esc(q.gold)}</td><td>${q.prediction===null?'未评分':q.correct?'正确':'错误'}</td></tr>`).join('')}</tbody></table></div>${r.error_message?`<p class="fineprint">${esc(r.error_message)}</p>`:''}`;}
async function init(){try{[data,meta,resultData]=await Promise.all([loadJSON('questions.json'),loadJSON('provenance.json'),loadJSON('results.json')]);$('#result-condition').onchange=renderResults;window.addEventListener('hashchange',route);route();}catch(e){$('#sample-content').innerHTML=`<div class="error">页面数据未能载入。请刷新重试。<br><small>${esc(e.message)}</small></div>`;}}
init();
